# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-08 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_auto_20170808_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='project_kor_name',
            field=models.CharField(help_text='\ud504\ub85c\uc81d\ud2b8\uc758 \ud55c\uae00 \uc774\ub984\uc744 \uc785\ub825\ud558\uc138\uc694', max_length=200, verbose_name='\ud504\ub85c\uc81d\ud2b8 \uad6d\ubb38\uc774\ub984'),
        ),
    ]
