# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-08 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_auto_20170808_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='reg_date',
            field=models.DateField(help_text='\uc624\ub298\uc77c\uc790 \ub610\ub294 \uc6d0\ud558\ub294 \uc77c\uc790\ub97c \uc120\ud0dd\ud558\uc138\uc694', verbose_name='\ub4f1\ub85d\uc77c\uc790'),
        ),
    ]
