# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-09 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_auto_20170809_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='project_kor_name',
            field=models.CharField(error_messages={b'required': '\ud504\ub85c\uc81d\ud2b8 \uad6d\ubb38\uc774\ub984\uc744 \uc785\ub825\ud558\uc138\uc694'}, help_text='\ud504\ub85c\uc81d\ud2b8\uc758 \ud55c\uae00 \uc774\ub984\uc744 \uc785\ub825\ud558\uc138\uc694', max_length=200, verbose_name='1. \ud504\ub85c\uc81d\ud2b8 \uad6d\ubb38\uc774\ub984'),
        ),
    ]
