# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-09 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0008_auto_20170809_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_kor_name', models.CharField(help_text='\ud504\ub85c\uc81d\ud2b8\uc758 \ud55c\uae00 \uc774\ub984\uc744 \uc785\ub825\ud558\uc138\uc694', max_length=200, verbose_name='\ud504\ub85c\uc81d\ud2b8 \uad6d\ubb38\uc774\ub984')),
                ('project_eng_name', models.CharField(help_text='\ud504\ub85c\uc81d\ud2b8\uc758 \uc601\ubb38 \uc774\ub984\uc744 \uc785\ub825\ud558\uc138\uc694', max_length=200, verbose_name='\ud504\ub85c\uc81d\ud2b8 \uc601\ubb38\uc774\ub984')),
                ('making_year', models.CharField(help_text='ex) 2017', max_length=4, verbose_name='\uc81c\uc791\ub144\ub3c4')),
                ('making_month', models.CharField(help_text='ex) 12', max_length=2, verbose_name='\uc81c\uc791\uc6d4')),
                ('project_kind', models.CharField(choices=[('W1', 'Web'), ('M1', 'Mobile'), ('A1', 'App'), ('V1', 'Video'), ('O1', 'Other')], default='W1', help_text='\ud504\ub85c\uc81d\ud2b8 \uc885\ub958\ub97c \uc120\ud0dd\ud558\uc138\uc694', max_length=2, verbose_name='\ud504\ub85c\uc81d\ud2b8 \uc885\ub958')),
                ('project_summary', models.TextField(help_text='\ud504\ub85c\uc81d\ud2b8 \uc694\uc57d\uc744 \uc785\ub825\ud558\uc138\uc694', max_length=1000, verbose_name='\ud504\ub85c\uc81d\ud2b8 \uc694\uc57d')),
                ('project_period', models.CharField(help_text='ex) 2017.01 ~ 2017.12', max_length=30, verbose_name='\ud504\ub85c\uc81d\ud2b8 \uae30\uac04')),
                ('project_range', models.CharField(max_length=500, verbose_name='\ud504\ub85c\uc81d\ud2b8 \ubc94\uc704')),
                ('client_name', models.CharField(max_length=100, verbose_name='\uace0\uac1d\uc0ac \uc774\ub984')),
                ('producer', models.CharField(max_length=100, verbose_name='\uc81c\uc791\uc0ac \uc774\ub984')),
                ('bg_image', models.ImageField(help_text='width, height\uc9c0\uc815\ud544\uc694', max_length=200, upload_to='images/%Y%m%d', verbose_name='\ubc31\uadf8\ub77c\uc6b4\ub4dc \uc774\ubbf8\uc9c0')),
                ('thumb_image', models.ImageField(help_text='width, height\uc9c0\uc815\ud544\uc694', max_length=200, upload_to='images/%Y%m%d', verbose_name='\uc378\ub124\uc77c \uc774\ubbf8\uc9c0')),
                ('main_image', models.ImageField(help_text='width, height\uc9c0\uc815\ud544\uc694', upload_to='images/%Y%m%d', verbose_name='\uba54\uc778 \uc774\ubbf8\uc9c0')),
                ('sub_image01', models.ImageField(help_text='--', null=True, upload_to='images/%Y%m%d', verbose_name='\uc11c\ube0c \uc774\ubbf8\uc9c001')),
                ('sub_image02', models.ImageField(help_text='--', null=True, upload_to='images/%Y%m%d', verbose_name='\uc11c\ube0c \uc774\ubbf8\uc9c002')),
                ('sub_image03', models.ImageField(help_text='--', null=True, upload_to='images/%Y%m%d', verbose_name='\uc11c\ube0c \uc774\ubbf8\uc9c003')),
                ('sub_image04', models.ImageField(help_text='--', null=True, upload_to='images/%Y%m%d', verbose_name='\uc11c\ube0c \uc774\ubbf8\uc9c004')),
                ('icon_image', models.ImageField(help_text='--', null=True, upload_to='images/%Y%m%d', verbose_name='\uc544\uc774\ucf58 \uc544\ubbf8\uc9c0')),
                ('mobile_image', models.ImageField(help_text='--', null=True, upload_to='images/%Y%m%d', verbose_name='\ubaa8\ubc14\uc77c \uc774\ubbf8\uc9c0')),
                ('video_url', models.TextField(help_text='vimeo\uc601\uc0c1 url\uc18c\uc2a4\ub97c \uc785\ub825\ud558\uc138\uc694', null=True, verbose_name='\uc601\uc0c1 URL')),
                ('open_yn', models.CharField(choices=[('Y', '\uacf5\uac1c'), ('N', '\ube44\uacf5\uac1c')], default='Y', max_length=1, verbose_name='\uacf5\uac1c\uc5ec\ubd80')),
                ('show_order', models.IntegerField(help_text='ex) 10', verbose_name='\ub178\ucd9c\uc21c\uc11c')),
                ('reg_date', models.DateField(help_text='\uc624\ub298\uc77c\uc790 \ub610\ub294 \uc6d0\ud558\ub294 \uc77c\uc790\ub97c \uc120\ud0dd\ud558\uc138\uc694', verbose_name='\ub4f1\ub85d\uc77c\uc790')),
            ],
            options={
                'verbose_name': '\ud3ec\ud1a0\ud3f4\ub9ac\uc624',
                'verbose_name_plural': '\ud3ec\ud1a0\ud3f4\ub9ac\uc624',
            },
        ),
        migrations.DeleteModel(
            name='list',
        ),
    ]
