# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-11 02:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0009_auto_20170809_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='bg_image',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='bg_image_horizontal',
            field=models.ImageField(help_text='PC\uc5d0\uc11c \uc0ac\uc6a9 \ud560 \ubc30\uacbd\uc774\ubbf8\uc9c0 - width, height\uc9c0\uc815\ud544\uc694', max_length=200, null=True, upload_to='images/%Y%m%d', verbose_name='\ubc31\uadf8\ub77c\uc6b4\ub4dc \uc774\ubbf8\uc9c0(\uac00\ub85c\ud615)'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='bg_image_vertical',
            field=models.ImageField(help_text='MOBILE\uc5d0\uc11c \uc0ac\uc6a9 \ud560 \ubc30\uacbd \uc774\ubbf8\uc9c0 - width, height\uc9c0\uc815\ud544\uc694', max_length=200, null=True, upload_to='images/%Y%m%d', verbose_name='\ubc31\uadf8\ub77c\uc6b4\ub4dc \uc774\ubbf8\uc9c0(\uc138\ub85c\ud615)'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='main_image',
            field=models.ImageField(help_text='width, height\uc9c0\uc815\ud544\uc694', null=True, upload_to='images/%Y%m%d', verbose_name='\uba54\uc778 \uc774\ubbf8\uc9c0'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='thumb_image',
            field=models.ImageField(help_text='width, height\uc9c0\uc815\ud544\uc694', max_length=200, null=True, upload_to='images/%Y%m%d', verbose_name='\uc378\ub124\uc77c \uc774\ubbf8\uc9c0'),
        ),
    ]
